inherit_from:
  - .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.7
  Include:
    - "**/*.rb"
    - "features/**/*.rb"
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'bin/**'
    - 'lib/qaxpert/languages/language_handler.rb' # se for muito longo, ajuste depois


# Desabilita só o cop que está falhando
Style/SafeNavigation:
  Enabled: false
  
# Máximo de linhas em branco consecutivas em qualquer lugar
Layout/EmptyLines:
  Enabled: true
  Max: 1

# Linhas em branco antes e depois do *corpo* de métodos
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
  Max: 1

# Linhas em branco após guard clauses (return, next, break)
Layout/EmptyLineAfterGuardClause:
  Enabled: true
  Max: 1

# Linhas em branco após condições multilinha (if, unless, etc.)
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true
  Max: 1

# (Opcional) Linhas em branco ao redor do corpo de classes
Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Max: 1