require 'net/http'
require 'json'
require 'dotenv/load'
require 'uri'
require 'base64'

require_relative 'qaxpert/cli'
require_relative 'qaxpert/support/parser'
require_relative 'qaxpert/AI/ai_generator'
require_relative 'qaxpert/Utils/utils'
require_relative 'qaxpert/Integrations/gemini_client'
require_relative 'qaxpert/support/quality_scorer'
require_relative 'qaxpert/support/coverage_analyzer'
require_relative 'qaxpert/Utils/git_analyzer'
require_relative 'qaxpert/Utils/git_utils'
require_relative 'qaxpert/Integrations/jira_client'
