require 'net/http'
require 'json'
require 'dotenv/load'
require 'uri'
require 'base64'

require_relative 'qaxpert/cli'
require_relative 'qaxpert/parser'
require_relative 'qaxpert/ai_generator'
require_relative 'qaxpert/utils'
require_relative 'qaxpert/gemini_client'
require_relative 'qaxpert/quality_scorer'
require_relative 'qaxpert/coverage_analyzer'
require_relative 'qaxpert/git_analyzer'
require_relative 'qaxpert/git_utils'
require_relative 'qaxpert/jira_client'
